=== folio-org/mod-remote-storage/src/main/resources/swagger.api/schemas/accessionQueue.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "Accession queue",
  "properties": {
    "id": {
      "description": "Accession queue id",
      "$ref": "uuid.json"
    },
    "itemBarcode": {
      "description": "Accession queue name",
      "type": "string"
    },
    "createdDateTime": {
      "description": "Created Date",
      "type": "string",
      "format": "date-time"
    },
    "accessionedDateTime": {
      "description": "Accessioned Date",
      "type": "string",
      "format": "date-time"
    },
    "remoteStorageId": {
      "description": "Remote storage id",
      "$ref": "uuid.json"
    },
    "callNumber": {
      "description": "Call number",
      "type": "string"
    },
    "instanceTitle": {
      "description": "Instance title",
      "type": "string"
    },
    "instanceAuthor": {
      "description": "Instance author",
      "type": "string"
    },
    "metadata": {
      "description": "Entity metadata",
      "type": "object",
      "$ref": "metadata.json"
    }
  },
  "additionalProperties": false,
  "required": []
}

=== folio-org/mod-remote-storage/src/main/resources/samples/accession_queue_record.json
{
  "id": "abe6bad7-3b30-3f1c-dee5-f653ded15636",
  "itemBarcode": "553285216744",
  "createdDateTime": "2021-02-19T17:27:38.524736500",
  "accessionedDateTime": "2021-02-19T17:29:38.524736500",
  "remoteStorageId": "d3cfdb9e-e364-4209-85e5-8f49fc0969b5",
  "callNumber": "1234567890",
  "instanceTitle": "Title sample",
  "instanceAuthor": "Matt Gordon "
}
