=== folio-org/mod-remote-storage/src/main/resources/swagger.api/schemas/retrievalQueue.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Retrieval queue",
  "type": "object",
  "properties": {
    "id": {
      "description": "Retrieval queue id",
      "$ref": "uuid.json"
    },
    "holdId": {
      "description": "Hold/request id",
      "type": "string"
    },
    "itemBarcode": {
      "description": "Item barcode",
      "type": "string"
    },
    "instanceTitle": {
      "description": "Instance title",
      "type": "string"
    },
    "instanceAuthor": {
      "description": "Instance author",
      "type": "string"
    },
    "callNumber": {
      "description": "Call number",
      "type": "string"
    },
    "patronBarcode": {
      "description": "Patron barcode",
      "type": "string"
    },
    "patronName": {
      "description": "Patron name",
      "type": "string"
    },
    "retrievedDateTime": {
      "description": "Retrieved date",
      "type": "string",
      "format": "date-time"
    },
    "pickupLocation": {
      "description": "Pickup location",
      "type": "string"
    },
    "requestStatus": {
      "description": "Request status",
      "type": "string"
    },
    "requestNote": {
      "description": "Request note",
      "type": "string"
    },
    "createdDateTime": {
      "description": "Request Date",
      "type": "string",
      "format": "date-time"
    },
    "remoteStorageId": {
      "description": "Remote storage id",
      "$ref": "uuid.json"
    },
    "metadata": {
      "description": "Entity metadata",
      "type": "object",
      "$ref": "metadata.json"
    }
  },
  "additionalProperties": false,
  "required": []
}

=== folio-org/mod-remote-storage/src/main/resources/samples/retrieval_queue_record.json
{
  "id": "be16bad7-2a30-4f1c-bee5-f653ded15627",
  "holdId": "7babb1ab-f46f-4c74-8950-bda779440f6f",
  "itemBarcode": "326585216743",
  "instanceTitle": "Title sample",
  "instanceAuthor": "Matt Gordon",
  "callNumber": "1234567890",
  "patronBarcode": "543285216734",
  "patronName": "John Smith",
  "retrievedDateTime": "2021-02-19T17:29:38.524736500",
  "pickupLocation": "KU/CC/DI",
  "requestStatus": "Open - Not yet filled",
  "requestNote": "request note sample",
  "createdDateTime": "2021-02-19T17:27:38.524736500",
  "remoteStorageId": "d3cfdb9e-e364-4209-85e5-8f49fc0969b5"
}
